{{- if .Values.persistence.workspace.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-workspace
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.workspace.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.workspace.size }}
  {{- if .Values.persistence.workspace.storageClassName }}
  storageClassName: {{ .Values.persistence.workspace.storageClassName | quote }}
  {{- end }}
{{- end }}
